// <auto-generated />
using HopDelivery.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HopDelivery.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260603083500_SemillaCervezas")]
    partial class SemillaCervezas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("HopDelivery.API.Entities.Catalogos.CatMarca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("CatMarcas");
                });

            modelBuilder.Entity("HopDelivery.API.Entities.Cerveza", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("ABV")
                        .HasColumnType("double");

                    b.Property<int>("Calificacion")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("IBU")
                        .HasColumnType("int");

                    b.Property<int>("IdMarca")
                        .HasColumnType("int");

                    b.Property<string>("ImagenURL")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Cervezas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ABV = 4.5,
                            Calificacion = 4,
                            Descripcion = "Lager clara muy refrescante.",
                            IBU = 0,
                            IdMarca = 0,
                            ImagenURL = "",
                            Nombre = "Corona Extra",
                            Tipo = "Lager"
                        },
                        new
                        {
                            Id = 2,
                            ABV = 4.2000000000000002,
                            Calificacion = 5,
                            Descripcion = "Stout oscura con espuma cremosa.",
                            IBU = 0,
                            IdMarca = 0,
                            ImagenURL = "",
                            Nombre = "Guinness Draught",
                            Tipo = "Stout"
                        },
                        new
                        {
                            Id = 3,
                            ABV = 5.4000000000000004,
                            Calificacion = 4,
                            Descripcion = "IPA escocesa con notas frutales.",
                            IBU = 0,
                            IdMarca = 0,
                            ImagenURL = "",
                            Nombre = "Punk IPA",
                            Tipo = "IPA"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
